name: Go

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches: '*'

jobs:
  build:
    strategy:
      matrix:
        go: ['1.16', '1.17']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: go env -w GO111MODULE=auto
    - run: go get gopkg.in/yaml.v2
    - run: go build -v ./...
    - run: go test -v ./...
  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - run: go env -w GO111MODULE=auto
    - run: go get github.com/mattn/goveralls
    - run: go get github.com/axw/gocov/gocov
    - run: go get code.google.com/p/go.tools/cmd/cover
    - run: export PATH="$HOME/gopath/bin:$PATH"
    - run: goveralls -package "github.com/woothee/woothee-go" -service=travis-ci
