name: Go

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches: '*'

jobs:
  build:
    strategy:
      matrix:
        go: ['1.16', '1.17']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: go mod download
    - run: go build -v ./...
    - run: go test -race -covermode atomic -coverprofile=covprofile ./...
    - run: go install github.com/mattn/goveralls@latest
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github
